### PR TITLE
fix: optional fields from `publishConfig`

### PR DESCRIPTION
**Pull request by sxzz**

### CODE REVIEW

**Comment by sxzz** [comment]
@pi0 Could you review this, or should I merge the PR directly?

**Comment by pi0** [comment]
Please do not merge PRs unless you are explicit maintainer of repository.

https://github.com/unjs/governance

**Comment by sxzz** [comment]
It's been over two months since I submitted PR https://github.com/unjs/pkg-types/pull/193. I've also pinged you during this time, but there hasn't been any response.

If merging is an issue, I apologize and feel free to revert it.

**Comment by pi0** [comment]
PR is fine. I didn't merge because had to investigate why our tests didn't catch it).

You could reach out again if it was a critical issue. we have several communication channels.

As an open-source maintainer, you would understand why PRs can get delayed to land. (

**Pull request merged**
